### ISSUE TITLE
Implicit change sequence order assumptions

### ISSUE THREAD

**Issue by JanWittler** [vitruv-tools/Vitruv-Applications-ComponentBasedSystems#163]
This issue raises awareness for a topic already mentioned in vitruv-tools/Vitruv-Applications-ComponentBasedSystems#138 .

For (almost) all our current applications, we make strong assumptions about the order in which objects are created. In particular, it is expected that an object is named before it is inserted (otherwise the `createOrFind` pattern does not work) and even more critical, all other changes to the object are expected to be executed **after** the insertion. If this is not the case, changes to an object performed prior to insertion are lost in the target model, as all such routines require an already setup correspondence. Currently, this can only be fixed by updating all attributes of an object when it is created, leading to a lot of code duplication (thus it's never done in the current code).

Therefore, it was desirable to solve this in the future as part of the language / the engine. Approaches for this could be to automatically reorder the changes such that naming and insertion are performed first. Another approach could be to extend the language by some `await correspondence` construct which queues up the routine until some correspondence is created. Furthermore, currently we assume for `createOrFind` to work that an object is inserted and named thus it would make sense to allow compound triggers only for creation scenarios with required values, like `created and features [name, eContainer] set`.

Relates to vitruv-tools/Vitruv-DSLs#32

**Comment by HeikoKlare** [comment]
It's great that you bring that topic up. And I totally agree: we have these assumptions about the order of changes, for which one might say that the transformations with these assumptions only work "by accident". We have been knowing this for a long time and in some transformations, we have already considered how "correct solutions" (to be explained in the following) have to look like. But as you point out, most transformations make (too) strong assumptions that will not always hold.

First, I want to make some extensions to the discussion about what we would like to have, because from my point of view it is essentially not about change orders, as it's not that simple as only having a rename before an insertion (because that is also a strong assumption about how transformations work that does not always hold). Instead, it is about how changes are or have to be processed. In fact, many transformations (at least the ones we consider), even if implemented imperatively and change-driven, are _relational_. They match some pattern and in case a pattern matches they create some other pattern, which is then kept consistent afterwards. This is how relational languages, such as our Mappings language, work by design.
An imperative language like the Reactions language requires you to implement that mechanism by hand. What you are mentioning is about the fact that a pattern is not matched when an element is inserted, but some additional requirements (like the name being set) have to be met.
To properly implement such a pattern matching in the Reactions language, you have to think about these patterns and basically define a Reaction for each change that might lead to fulfillment of the pattern, check whether it is fulfilled (by investigating the model) and then transforming all the information required in that transformation rule (and potentially dependent rules that need to be triggered).
Luckily, the situations that we have considered so far do not require a complex pattern matching, which is why reacting to element insertions worked in most cases. But, as you point out, we are coming to the limits of that approach.

In consequence, the same applies to the `createOrFind` pattern. Its application has to be delayed until all information required for a pattern match are given. This does _not_ mean that only the name of the element must have been set. Since most elements can be uniquely identified by their names, this works out for most of the scenarios we have by now, but actually this is only a "case-specific-sufficient" solution, but not a conceptually sophisticated one. This is also why enforcing a specific change order is not reasonable (change order depends on how changes occurred, not how they are used) and, unfortunately, not an ultimate solution either.

We can, of course, discuss how to improve the Reactions language to support this pattern matching properly. However, there is the risk that we result in an overly complex language that partly replaces the Mappings language, which is actually intended to provide the relational specification of transformations, from which the required pattern matching is automatically derived. Originally, the Mappings language was intended to be used whereever possible (to abstract away from manually performing pattern matching) and to only use or adapt Reactions where necessary. Since the language is not in a state that can be used productively, we may either make that language ready-to-use, or throw it away and grow the Reactions to a one-fits-all solution. As a side note: Instead of the Mappings we may even use the Commonalities language as an even more sophisticated replacement.
My opinion is that putting too much abstraction into the Reactions is not a good approach, because it was intended to be a quite basic language only abstracting from the essential parts of transformations (and since not all transformations are relational, having pattern matching as a first-class element of the language may not be reasonable). I would even propose to throw away some of the abstraction of the Reactions language (such as compound changes---which we have already dicussed-- and implementing the routine actions via an internal DSL only) to keep it as simple as possible.

As you see from my post, this is a quite complex topic that we should discuss in a meeting and figure out how to proceed with the transformation language we have. It requries some holistic considerations and discussion, such that we should not implement some quick-shot solutions for that.

**Comment by JanWittler** [comment]
As further steps regarding this issue require a longterm roadmap regarding our DSLs, I moved the issue into a discussion: https://github.com/orgs/vitruv-tools/discussions/3
